# ref: https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - 'ğŸ“¦ï¸ Dependencies'
    commit-message:
      # prefix: 'â¬†ï¸ '
      # include: 'scope'
      prefix: 'â¬†ï¸ (deps) '
      prefix-development: 'â¬†ï¸ (deps-dev) '
    target-branch: 'main'
    # handle these via human
    ignore:
      - dependency-name: '@radix-ui/*'
      - dependency-name: '@types/node'
      - dependency-name: 'kbar'
      - dependency-name: 'inquirer'
      - dependency-name: 'read-pkg-up'
      - dependency-name: 'typescript'
